const catalogTypes={
 pidols:{title:"P Idol ทั้งหมด",lead:"ค้นหาและเปรียบเทียบ P Idol ตาม Plan, Tier, กลไก และวิธีได้รับ",data:()=>window.pidols,source:"https://game8.jp/gakuen-idolmaster/609097",label:"P Idol"},
 supports:{title:"Support Card ทั้งหมด",lead:"ฐานข้อมูล Support Card ทุกระดับ พร้อม Tier, ประเภทค่าสถานะ และ Plan",data:()=>window.supportCards,source:"https://game8.jp/gakuen-idolmaster/609102",label:"Support Card"},
 skills:{title:"Skill Card ทั้งหมด",lead:"ตรวจเอฟเฟกต์และเงื่อนไขของ Skill Card แยกตาม Plan และระดับ",data:()=>window.skillCards,source:"https://game8.jp/gakuen-idolmaster/609737",label:"Skill Card"},
 items:{title:"P Item ทั้งหมด",lead:"รวม P Item สำหรับทุก Plan พร้อมคำอธิบายเอฟเฟกต์",data:()=>window.pItems,source:"https://game8.jp/gakuen-idolmaster/610077",label:"P Item"},
 drinks:{title:"P Drink ทั้งหมด",lead:"รวม P Drink, ระดับ PLv ที่ปลดล็อก และเอฟเฟกต์",data:()=>window.pDrinks,source:"https://game8.jp/gakuen-idolmaster/611910",label:"P Drink"}
};
const params=new URLSearchParams(location.search),type=catalogTypes[params.get("type")]?params.get("type"):"pidols",config=catalogTypes[type],data=config.data();
const $=s=>document.querySelector(s),escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
document.title=`${config.title} — GAKUMAS TH`;$("#catalogTitle").textContent=config.title;$("#catalogLead").textContent=config.lead;$("#catalogTotal").textContent=data.length;$("#crumbCurrent").textContent=config.label;$("#catalogCredit").innerHTML=`Original guide/content: <a href="${config.source}" target="_blank" rel="noreferrer">Game8 — เปิดหน้ารวมต้นฉบับ ↗</a>`;
const canonicalUrl=`https://finnkun.github.io/gakumas-th-guide/catalog.html?type=${type}`;let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement("link");canonical.rel="canonical";document.head.append(canonical)}canonical.href=canonicalUrl;
const rarity=[...new Set(data.map(x=>x.rarity).filter(Boolean))];$("#catalogRarity").innerHTML='<option value="all">ทั้งหมด</option>'+rarity.map(x=>`<option>${escapeHtml(x)}</option>`).join("");if(!rarity.length)$("#rarityField").hidden=true;
function cardMeta(x){if(type==="pidols")return [x.tier,x.plan,x.style,x.obtain];if(type==="supports")return [x.tier,x.type,x.plan,x.obtain];if(type==="skills")return [x.rarity,x.plan];if(type==="drinks")return [x.plan,`PLv ${x.unlock}`];return [x.plan]}
function cardText(x){return x.effect||x.note||`${x.rarity||""} ${x.obtain||""}`}
const pageSize=24;let visible=pageSize;
function syncUrl(){const url=new URL(location.href);const values={q:$("#catalogSearch").value.trim(),plan:$("#catalogPlan").value,rarity:$("#catalogRarity").value};Object.entries(values).forEach(([key,value])=>value&&value!=="all"?url.searchParams.set(key,value):url.searchParams.delete(key));history.replaceState(null,"",url)}
function render(reset=false){if(reset)visible=pageSize;const q=$("#catalogSearch").value.trim(),plan=$("#catalogPlan").value,rarity=$("#catalogRarity").value;const list=data.filter(x=>(plan==="all"||x.plan===plan)&&(rarity==="all"||x.rarity===rarity)&&window.GakumasSearch.matches(x,q));const shown=list.slice(0,visible);$("#catalogCount").textContent=`${shown.length} จาก ${list.length}`;$("#catalogEmpty").hidden=!!list.length;$("#catalogLoadMore").hidden=shown.length>=list.length;$("#catalogGrid").innerHTML=shown.map(x=>`<a class="catalog-card" href="detail.html?type=${type}&id=${encodeURIComponent(x.id)}"><div class="catalog-image"><img src="${escapeHtml(x.image||"assets/app-icon.svg")}" alt="${escapeHtml(x.name)}" loading="lazy" decoding="async" onerror="this.src='assets/app-icon.svg'"><span>${escapeHtml(x.rarity||x.tier||"")}</span></div><div class="catalog-card-body"><div class="card-chips">${cardMeta(x).filter(Boolean).slice(0,3).map(v=>`<span>${escapeHtml(v)}</span>`).join("")}</div><div class="catalog-card-title" lang="ja">${escapeHtml(x.short||x.name)}</div><p>${escapeHtml(cardText(x)).slice(0,145)}</p><b>ดูรายละเอียด ${escapeHtml(x.short||x.name)} →</b></div></a>`).join("");syncUrl()}
$("#catalogSearch").value=params.get("q")||"";$("#catalogPlan").value=params.get("plan")||"all";$("#catalogRarity").value=params.get("rarity")||"all";
[$("#catalogSearch"),$("#catalogPlan"),$("#catalogRarity")].forEach(x=>x.addEventListener("input",()=>render(true)));$("#catalogLoadMore").addEventListener("click",()=>{visible+=pageSize;render()});$("#catalogReset").addEventListener("click",()=>{$("#catalogSearch").value="";$("#catalogPlan").value="all";$("#catalogRarity").value="all";render(true)});
const menu=$("#shellMenu"),nav=document.querySelector(".site-header nav");menu.addEventListener("click",()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",open)});render();
