const detailTypes={pidols:{label:"P Idol",data:()=>window.pidols},supports:{label:"Support Card",data:()=>window.supportCards},skills:{label:"Skill Card",data:()=>window.skillCards},items:{label:"P Item",data:()=>window.pItems},drinks:{label:"P Drink",data:()=>window.pDrinks}};
const params=new URLSearchParams(location.search),type=params.get("type")||document.body.dataset.type,config=detailTypes[type],id=params.get("id")||document.body.dataset.id,$=s=>document.querySelector(s),escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function facts(item){const fields=type==="pidols"?[["Tier",item.tier],["Plan",item.plan],["กลไก",item.style],["ระดับ",item.rarity],["วิธีได้รับ",item.obtain]]:type==="supports"?[["Tier",item.tier],["ประเภท",item.type],["Plan",item.plan],["ระดับ",item.rarity],["วิธีได้รับ",item.obtain]]:type==="skills"?[["Plan",item.plan],["ระดับ",item.rarity]]:type==="drinks"?[["Plan",item.plan],["ปลดล็อก",`PLv ${item.unlock}`]]:[["Plan",item.plan]];return fields.filter(x=>x[1]).map(([k,v])=>`<div><dt>${escapeHtml(k)}</dt><dd>${escapeHtml(v)}</dd></div>`).join("")}
function renderDeep(source){
 const article=window.deepDetails?.[source];if(!article?.sections?.length)return;
 const renderBlock=block=>block.type==="p"?`<p>${escapeHtml(block.text)}</p>`:block.type==="list"?`<${block.ordered?"ol":"ul"}>${block.items.map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</${block.ordered?"ol":"ul"}>`:`<div class="deep-table-wrap"><table>${block.rows.map((row,i)=>`<tr>${row.map(cell=>`<${i===0?"th":"td"}>${escapeHtml(cell)}</${i===0?"th":"td"}>`).join("")}</tr>`).join("")}</table></div>`;
 let original=false;
 const paint=()=>{const selected=original&&article.originalSections?.length?article.originalSections:article.sections;const sections=selected.map((section,index)=>({...section,anchor:`section-${index+1}`}));$("#deepContent").innerHTML=`<div class="deep-heading"><span>${original?"ข้อมูลต้นฉบับภาษาญี่ปุ่น":"คำแปลภาษาไทยฉบับเต็ม"}</span><div class="deep-heading-actions">${article.updated?`<small>อัปเดต ${escapeHtml(article.updated)}</small>`:""}${article.originalSections?.length?`<button class="language-toggle" type="button">${original?"แสดงคำแปลไทย":"ดูต้นฉบับญี่ปุ่น"}</button>`:""}</div></div>`+sections.map(section=>`<section class="deep-section"${original?' lang="ja"':""}><h${section.level} id="${section.anchor}">${escapeHtml(section.title)}</h${section.level}>${section.blocks.map(renderBlock).join("")}</section>`).join("");const toc=$("#detailToc");toc.hidden=false;toc.querySelector("nav").innerHTML=sections.map(section=>`<a class="level-${section.level}" href="#${section.anchor}">${escapeHtml(section.title)}</a>`).join("");$(".language-toggle")?.addEventListener("click",()=>{original=!original;paint()})};paint()
}
if(!config){$("#detailMissing").hidden=false;document.querySelector(".detail-hero").hidden=true;document.querySelector(".detail-layout").hidden=true}else{const data=config.data(),item=data.find(x=>String(x.id)===String(id));if(!item){$("#detailMissing").hidden=false;document.querySelector(".detail-hero").hidden=true;document.querySelector(".detail-layout").hidden=true}else{document.title=`${item.short||item.name} — ${config.label} | GAKUMAS TH`;$("#detailCategory").textContent=config.label;$("#detailCategory").href=`catalog.html?type=${type}`;$("#detailCrumb").textContent=item.short||item.name;$("#detailType").textContent=config.label.toUpperCase();$("#detailTitle").textContent=item.short||item.name;$("#detailSubtitle").textContent=item.short&&item.name!==item.short?item.name:"ข้อมูลแปลและเรียบเรียงภาษาไทย";$("#detailImage").src=item.image||"assets/app-icon.svg";$("#detailImage").alt=item.name;$("#detailImage").onerror=()=>{$("#detailImage").src="assets/app-icon.svg"};$("#detailRarity").textContent=item.rarity||item.tier||"";$("#detailTags").innerHTML=[item.plan,item.tier,item.type,item.style].filter(Boolean).map(x=>`<span>${escapeHtml(x)}</span>`).join("");$("#detailFacts").innerHTML=`<dl>${facts(item)}</dl>`;$("#detailEffect").innerHTML=`<h3>${type==="skills"||type==="items"||type==="drinks"?"เอฟเฟกต์":"สรุปการใช้งาน"}</h3><p>${escapeHtml(item.effect||item.note||"ตรวจรายละเอียดเพิ่มเติมจากหน้าต้นฉบับ")}</p>`;$("#detailSource").href=item.source||"https://game8.jp/gakuen-idolmaster";$("#backCatalog").href=`catalog.html?type=${type}`;const related=data.filter(x=>x.id!==item.id&&(x.plan===item.plan||x.type&&x.type===item.type)).slice(0,5);$("#relatedList").innerHTML=related.map(x=>`<a href="detail.html?type=${type}&id=${encodeURIComponent(x.id)}"><img src="${escapeHtml(x.image||"assets/app-icon.svg")}" alt="" loading="lazy"><span><b>${escapeHtml(x.short||x.name)}</b><small>${escapeHtml(x.plan||x.type||"")}</small></span></a>`).join("")}}
if(config){const activeItem=config.data().find(x=>String(x.id)===String(id));if(activeItem){renderDeep(activeItem.source);$("#detailMissing")?.remove()}}
const menu=$("#shellMenu"),nav=document.querySelector(".site-header nav");menu.addEventListener("click",()=>{const open=nav.classList.toggle("open");menu.setAttribute("aria-expanded",open)});
